### ISSUE TITLE
undefined symbol: mongoc_database_drop_with_opts 

### ISSUE THREAD

**Issue by arsperger** [neoxic/lua-mongo#3]
Hi,

libmongoc-1.0-0
1.9.3+dfsg-2

lua-mongo
   1.0.0-1 (installed) - /usr/local/lib/luarocks/rocks

Got this error when trying to load the driver
local mongo = require 'mongo'

```
lua: error loading module 'mongo' from file '/usr/local/lib/lua/5.1/mongo.so':
        /usr/local/lib/lua/5.1/mongo.so: undefined symbol: mongoc_database_drop_with_opts
```

by the way does it support replica set? 

Thanks,
Arsen

**Comment by neoxic** [comment]
What system are you on? `luarocks` is unable to check versions of external dependencies. I suspect your `lua-mongo` module is linked against an older version of `mongoc` because `mongoc_database_drop_with_opts()` is around since `mongoc-1.7.0`.

Please check ldd's output for your `mongo.so` instance:
```
ldd /usr/local/lib/lua/5.1/mongo.so
```
to make sure it's linked against the correct version (1.9.0 or higher).

Additionally, you could try building with CMake which will strict check versions of installed dependencies prior to building and enable you to run tests. This could be helpful to discover more about the issue.

**Comment by neoxic** [comment]
> by the way does it support replica set?

`lua-mongo` is a binding to `mongo-c-driver`, so it virtually supports everything that is supported by the underlying driver (within the provided API, of course). Since replica set is supported by the driver, it is supported by `lua-mongo` as well. Check out this link for example: https://docs.mongodb.com/manual/reference/connection-string/#replica-set-option

**Comment by arsperger** [comment]
Hey Arseny,
Thanks for your quick response.

I am on Debian 8, here is the output of  ` ldd /usr/local/lib/lua/5.1/mongo.so`

```
linux-vdso.so.1 (0x00007ffe051bc000)
        libmongoc-1.0.so.0 => /usr/lib/libmongoc-1.0.so.0 (0x00007f070b163000)
        libbson-1.0.so.0 => /usr/lib/libbson-1.0.so.0 (0x00007f070af36000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f070ab8b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f070a88a000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f070a682000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f070a465000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f070b59c000)
```

I have installed libmongoc from Debian testing repo

`libmongoc-1.0-0                  1.9.3+dfsg-2                       amd64        MongoDB C client library - runtime files`

Thanks,
Arsen.

**Comment by neoxic** [comment]
No worries, man!

Now let's see what your
```
$ nm -D /usr/lib/libmongoc-1.0.so | grep mongoc_database_drop
```
has to say.

On my Arch with libmongoc-1.9.3, it produces the following:
```
$ nm -D /usr/lib/libmongoc-1.0.so | grep mongoc_database_drop
000000000002f800 T mongoc_database_drop
000000000002f6d0 T mongoc_database_drop_with_opts
```
which shows that `mongoc_database_drop_with_opts()` is defined.

If your output is different, the version of the underlying binaries the package contains is probably far from 1.9.3 to say the least. Try uninstalling the package and building `libmongoc` from source. For example, this is what we do on our Debian Stretch images:
```
# libmongoc
wget https://github.com/mongodb/mongo-c-driver/releases/download/1.9.3/mongo-c-driver-1.9.3.tar.gz
tar -xvzf mongo-c-driver-1.9.3.tar.gz
cd mongo-c-driver-1.9.3
./configure --enable-extra-align=no
make
make install

# lua-mongo
luarocks install lua-mongo 1.1.0
```
and it works without a hitch.

After you have done the above, repeat the `ldd` and `nm` checks you've made to make sure `lua-mongo` is linked against the correct .so-library (the one that you built and installed from source).

**Comment by arsperger** [comment]
I've rebuilt libmongoc and it works like a charm now even with replica set :)
Thanks for your great support!
