### ISSUE TITLE
Openrety nginx log show '2018/08/17 23:37:54 [notice] 2603#2603: signal 17 (SIGCHLD) received from 2604 2018/08/17 23:37:54 [notice] 2603#2603: worker process 2604 exited with code 0 2018/08/17 23:37:54 [notice] 2603#2603: exit'

### ISSUE THREAD

**Issue by foxericlee** [neoxic/lua-mongo#8]
When I execute 'local mongo = require("mongo")'. The nginx logs show as blow.

2018/08/17 23:37:54 [notice] 2603#2603: signal 17 (SIGCHLD) received from 2604
2018/08/17 23:37:54 [notice] 2603#2603: worker process 2604 exited with code 0
2018/08/17 23:37:54 [notice] 2603#2603: exit

I have a clean centos 7.3. install newest openresty. Use the newest cmake and mongo-c-driver to build the mongo.so.

**Comment by neoxic** [comment]
Does the issue persist when you use pure Lua? I have no idea about openresty, to be honest. You might want to address this issue directly to openresty authors.

**Comment by neoxic** [comment]
As far as I can see, a Lua module may have to be patched first in some specific way to be suitable for use with OpenResty because OpenResty uses Nginx's core API for asynchronous I/O. There might be little to no sense to use an arbitrary Lua module as is with OpenResty since in that case, all I/O operations will be blocking. As for `lua-mongo`, one will have to patch (rewrite?) the underlying `mongo-c-driver` to make it use Nginx's ecosystem which does not seem to be an easy task.

**Comment by neoxic** [comment]
Reporter did not come back. Closing...
